# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    project_url: '%env(resolve:PROJECT_URL)%'
    app.default_locale: uk
    app.locales:
        - en
        - uk
    noValue: ''
    captchaPublicKey: '%env(EWZ_RECAPTCHA_SITE_KEY)%'
    googleAnalyticsID: '%env(default:noValue:GOOGLE_ANALYTICS_ID)%'
    googleAnalyticsKey: '%env(default:noValue:GOOGLE_ANALYTICS_KEY)%'
