controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

cabinet_root:
    path: /cabinet
    controller: App\Controller\CabinetController::index

cabinet_catch_routes:
    path: /cabinet/{reactRoute}
    controller: App\Controller\Cabinet\CabinetController::index
    requirements:
        reactRoute: .*