imports:
    - { resource: 'parameters.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $env: '%kernel.environment%'

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_listener, event: 'prePersist' }
            - { name: doctrine.event_listener, event: 'onFlush' }
            - { name: doctrine.event_listener, event: 'loadClassMetadata' }

    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Menu/'
            - '../src/Kernel.php'
            - '../src/GraphQL/Notification/Type/NotificationInterface.php'

    # Breadcrumb menu builders
    App\Menu\BreadcrumbBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: breadcrumb, alias: breadcrumb }

    App\GraphQL\Common\Validator\EntityExistsValidator:
        tags: ['validator.constraint_validator']

    App\Service\PhoneFormatter:
        public: true

    App\Service\MailerService:
        arguments:
            $senderEmail: '%env(resolve:SENDER_EMAIL)%'
            $recipientEmail: '%env(resolve:MANAGER_EMAIL)%'

    App\Seo\SchemaOrgGenerator:
        arguments:
            $contactEmail: '%env(resolve:CONTACT_EMAIL)%'

    App\Service\Media\MediaService:
        arguments:
            $mediaBaseDir: '%kernel.project_dir%/public/upload/'
            $mediaBaseUrl: '%project_url%/upload/'

    App\Validator\Constraints\RecaptchaTrueValidator:
        arguments:
            $recaptcha: '@ewz_recaptcha.recaptcha'

    TheCodingMachine\GraphQLite\Bundle\Types\SymfonyUserInterfaceType:
        alias: 'App\GraphQL\User\Type\UserType'
        public: true
