{
  entityComments(
    entityType: "institutionUnit"
    entityId: 3762
    pagination:{
      limit: 2
      page: 2
    }
  ){
    items{
      id
      name
      text

      replies(pagination:{limit:2 page:3}){
        pageInfo{
          totalItems
        }
        items{
          id
          name
          text
          replyTo{
            id
            name
          }
        }
      }
    }
  }
}
