query {
  institution(id: 4){
    id
    slug
    name
    fullName
    description
    ownershipForm {
      name
      title
    }
  }

  institutions(pagination:{limit:2}){
    items{
      id
      name
    }
    pageInfo{
      page
      limit
      totalPages
      totalItems
    }
  }
}

mutation{
  editInstitution(id: 1, input:{
    name:"Центр сучасної естетичної стоматології NEW SMILE"
		fullName: "Центр сучасної естетичної стоматології NEW SMILE"
    description: null
  }){
    id
    name
    fullName
    description
  }
}
