{
  areas{
    items{
      id
      name
    }
  }

  districts(areaId:1 searchString: "Бах"){
    items{
      name
    }
  }

  cities(districtId:1 searchString:"ське"){
    items{
      name
      district{
        name
      }
    }
  }

	cityDistricts(cityId: 6802){
    items{
      name
      city{
        name
      }
    }
  }
}
