export const BASE_SETTINGS = {
    ENTRY_POINT_PADDING: 20,
    CANVAS_WIDTH: 800,
    CANVAS_HEIGHT: 600,
    CANVAS_BG_COLOR: "white",
    STROKE_WIDTH: 2,
    STROKE_COLOR: "black",
    TEXT_COLOR: "black",
    FONT_SIZE: 18,
    GRAVITY: 1,
    SPAWN_RATE: 1000,
    CTRL_GROUP: document.querySelector(".ctrl-group"),
};

export const HEADER_SETTINGS = {
    HEIGHT: 30,
    Z_INDEX: 1,
};

export const SHAPES_SETTINGS = {
    WIDTH: 110,
    HEIGHT: HEADER_SETTINGS.HEIGHT,
    OFFSET_X: BASE_SETTINGS.STROKE_WIDTH / 2,
    OFFSET_Y: BASE_SETTINGS.STROKE_WIDTH / 2,
    TEXT_OFFSET_X: 5 + BASE_SETTINGS.STROKE_WIDTH / 2,
    TEXT_OFFSET_Y: 5 + BASE_SETTINGS.STROKE_WIDTH / 2,
};

export const AREA_SETTINGS = {
    WIDTH: 150,
    HEIGHT: HEADER_SETTINGS.HEIGHT,
    OFFSET_X: SHAPES_SETTINGS.WIDTH + BASE_SETTINGS.STROKE_WIDTH / 2,
    OFFSET_Y: BASE_SETTINGS.STROKE_WIDTH / 2,
    TEXT_OFFSET_X: 5 + SHAPES_SETTINGS.WIDTH + BASE_SETTINGS.STROKE_WIDTH / 2,
    TEXT_OFFSET_Y: 5 + BASE_SETTINGS.STROKE_WIDTH / 2,
};

export const CONTENT_SETTINGS = {
    OFFSET_X: BASE_SETTINGS.STROKE_WIDTH / 2,
    OFFSET_Y: HEADER_SETTINGS.HEIGHT + BASE_SETTINGS.STROKE_WIDTH / 2,
};
