# See https://github.com/excelwebzone/EWZRecaptchaBundle for full configuration
ewz_recaptcha:
    version: 2
    hide_badge: true
    #score_threshold: 0.6
    locale_from_request: true
    public_key: '%env(EWZ_RECAPTCHA_SITE_KEY)%'
    private_key: '%env(EWZ_RECAPTCHA_SECRET)%'
    ajax: true
