# https://graphqlite.thecodingmachine.io/docs/symfony-bundle
graphqlite:
  namespace:
    controllers: App\GraphQL\
    types: [App\GraphQL]
  debug:
    INCLUDE_DEBUG_MESSAGE: false
    INCLUDE_TRACE: false
    RETHROW_INTERNAL_EXCEPTIONS: false
    RETHROW_UNSAFE_EXCEPTIONS: false
  security:
    enable_login: off
    enable_me: off
    firewall_name: api
    maximum_query_complexity: 314
    maximum_query_depth: 20
    introspection: true

when@dev:
  graphqlite:
    debug:
      INCLUDE_DEBUG_MESSAGE: true
      INCLUDE_TRACE: true