leogout_seo:
    # By default, the SEO generators services are not loaded if you don't configure them. The following default configuration
    # loads the services but they won't render anything.
    # See https://github.com/leogout/SeoBundle#configuration-reference to configure them.
    # See https://github.com/leogout/SeoBundle#setting-values-dynamically to use them directly in your controller.
    general:
        title: 'Медичні заклади України - Місто.юа'
    basic:
        title: 'Медичні заклади України - Місто.юа'
        description: 'Каталог медичних закладів та їх підрозділів - Контакти, адреси, телефони, факси, коди ЄДРПОУ'
        keywords: 'медичні заклади, підрозділи, контакти, адреси, телефони, факси, коди, ЄДРПОУ, Україна'
        canonical: '%project_url%/'
        robots:
            index: true
            follow: true
    og:
        title: "Медичні заклади України - Місто.юа"
        description: "Каталог медичних закладів та їх підрозділів - Контакти, адреси, телефони, факси, коди ЄДРПОУ"
        image: '%project_url%/img/logo_micto_200.png'
        type: website
        url: '%project_url%/'
    twitter: null
