nelmio_cors:
    defaults:
        allow_origin: ['*']  # Change '*' to your frontend URL in production
        allow_methods: ['GET', 'POST', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/graphql':
            origin_regex: true
            allow_origin: ['*']
            allow_methods: ['GET', 'POST', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
