twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes: ['form/custom_form_layout.html.twig']
  globals:
    captchaPublicKey: '%captchaPublicKey%'
    googleAnalyticsID: '%googleAnalyticsID%'
    googleAnalyticsKey: '%googleAnalyticsKey%'

when@test:
  twig:
    strict_variables: true
